//Shake.cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Shake : MonoBehaviour
{
    public float shakeForce = 10f;
    public float shakeThreshold = 1f;

    private Rigidbody2D rb;
    private Vector3 acceleration;

    void Start()
    {
        rb = GetComponent<Rigidbody2D>();

        // ภฬบฅฦฎ ธฎฝบณส ต๎ทฯ
        ScoreManager.instance.onFeverTimeStart += EnterFeverTime;
        ScoreManager.instance.onFeverTimeEnd += ExitFeverTime;
    }

    void Update()
    {
        if (ScoreManager.instance.isFeverTime)
        {
            // วฺตๅฦ๙ภว ฐกผำตต ผพผญ ตฅภฬลอ ฐกมฎฟภฑโ
            acceleration = Input.acceleration;

            // ฐกผำตต บฏฐๆภป ศ็ต้ธฒ ภำฐ่ฐชฐ๚ บ๑ฑณวฯฟฉ ศฎภฮ
            if (acceleration.sqrMagnitude >= shakeThreshold * shakeThreshold)
            {
                // ศ็ต้ธฒภฬ ฐจม๖ตวธ้ ฟ๒ม๗ภำ ภ๛ฟ๋
                Vector2 force = new Vector2(acceleration.x, acceleration.y) * shakeForce;
                rb.AddForce(force);
            }
        }
    }

    // ววน๖ลธภำ ม๘ภิ ฝร ม฿ทย มฆฐล
    void EnterFeverTime()
    {
        Debug.Log("ววน๖ลธภิ ตนภิ!");
        rb.gravityScale = 0f;
    }

    // ววน๖ลธภำ มพทแ ฝร ม฿ทย บนฑธ
    void ExitFeverTime()
    {
        rb.gravityScale = CatController.instance.GravityScale;
    }

    void OnDestroy()
    {
        // ภฬบฅฦฎ ธฎฝบณส วุมฆ
        ScoreManager.instance.onFeverTimeStart -= EnterFeverTime;
        ScoreManager.instance.onFeverTimeEnd -= ExitFeverTime;
    }
}
